= Java 7 et 8 sur BeagleBone Black (BBB)
Laurent HUET
2013-12-14
:jbake-type: post
:jbake-tags: beaglebone, jdk7, jdk8, ubuntu, performances
:jbake-status: published
:source-highlighter: prettify
:id: jdk7_jdk8_bbb
:icons: font

Mon second post est une réponse détaillée à une question posée par https://twitter.com/CodeStory/status/404649263134941185[@CodeStory] sur twitter.
140 caractères étaient largement insuffisants ! Ma réponse va également un peu plus loin puisque je compare les performances du JDK7 et du JDK8.

== Quel JDK pour BeagleBone Black ?
La première question qu'on peut se poser est : *Quelle version de JDK utiliser ?* +

Sur le site d'Oracle, on trouve 2 versions différentes pour le JDK 7:

* "Linux ARM v6/v7 Hard Float ABI"
* "Linux ARM v6/v7 Soft Float ABI"

Aucun JDK8 n'est proposé sur le site d'Oracle (pas encore de version finale). On trouve une "Early Access Release" sur https://jdk8.java.net/download.html[jdk8.java.net] sous le nom :

* "Linux ARMv6/7 VFP, HardFP ABI"

Ces JDK peuvent être utilisés sur BBB (ARM v7) et sur Raspberry Pi (ARM v6) ... mais pas sous n'importe quelle version d'OS.

=== Hard Float vs Soft Float
"Hard Float" et "Soft Float" sont des termes utilisés pour des jeux d'instruction spécifiques des processeurs ARM. Historiquement, le JDK d'Oracle n'était disponible qu'en version "Soft Float".
Quelques éléments de réponses se trouvent également dans les slides de mon quickie de Devoxx France 2013 sur http://parleys.com/play/5156c4d6e4b0c779d7881405[parleys]. +
Pour faire court, les JDK en version HFP (Hard Float) ne peuvent être utilisés que sur des OS compatible HFP.

=== Quel OS utiliser ?
La carte BBB est livrée avec une distribution Angström ... qui est compilée en "Soft Float". Seul le JDK 7 "Soft Float" peut donc être utilisé avec cet OS. Aucune version "Soft Float" du JDK 8 n'est disponible à ma connaissance.

Pour utiliser les JDK 7 et 8 en version HFP, il faut un Linux compatible. C'est le cas d'Ubuntu. Vous pouvez vous inspirez du http://learn.adafruit.com/beaglebone-black-installing-operating-systems/overview[tutoriel d'Adafruit] pour installer une nouvelle version d'OS sur la BBB ou, comme je l'ai fait, booter sur une microSD externe contenant Ubuntu.

== Tests de performances

J'ai repris les mêmes types de tests que pour mon http://parleys.com/play/5156c4d6e4b0c779d7881405[quickie de Devoxx France 2013], à savoir, des tests http://www.dacapobench.org/[dacapo] (avrora, fop et xalan). Les scores sont ramenés sur une base 100 ayant pour référence les résultats sur JDK7 sur Rapsberry Pi de mon Quickie. J'ai consigné les valeurs brutes dans un http://lhuet.github.io/blog/perfs_jdk7_jdk8_bbb.ods[fichier LibreOffice].

[NOTE]
Ces tests ont seulement pour objectif de comparer grossièrement les JDK ... et n'ont fait l'objet d'aucune méthodologie, analyse statistique, ... Pour avoir des résultats indiscutables, il faudrait des tests réalisés par des spécialistes de JVM, ce que je ne suis pas !


Voici donc 2 graphes avec/sans référence à la Raspberry Pi.
++++
<style type="text/css">
.legend {
    /* width: 13em; */
    /* border: 1px solid black; */
}

.legend .title {
    display: block;
    margin: 0.2em;
    border-style: solid;
    border-width: 0 0 0 1em;
    padding: 0 0.3em;
}
#perfWithRPiLegend, #perfWithoutRPiLegend {
    /* display: inline-block;
    position: absolute; */
    margin-top: 20px; 
}
#perfsWithRPi, #perfsWithoutRPi {
    margin-top:20px;
}
</style>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="row">
                    <div class="col-md-8">
                        <canvas id="perfsWithoutRPi"></canvas>
                    </div>
                    <div class="col-md-4">
                        <div id="perfWithoutRPiLegend"></div>
                    </div>
                </div>
                <div class="panel-footer text-center">JDK 7/8 SFP/HFP Beaglebone Black</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="row">
                    <div class="col-md-8">
                        <canvas id="perfsWithRPi"></canvas>
                    </div>
                    <div class="col-md-4">
                        <div id="perfWithRPiLegend"></div>
                    </div>
                </div>
                <div class="panel-footer text-center">JDK 7/8 SFP/HFP BBB et Raspberry Pi</div>
            </div>
        </div>
    </div>
</div>

<script src="/blog/js/Chart.min.js"></script>
<script>
/* https://github.com/bebraw/Chart.js.legend */
function legend(parent, data) {
    parent.className = 'legend';
    var datas = data.hasOwnProperty('datasets') ? data.datasets : data;

    datas.forEach(function(d) {
        var title = document.createElement('span');
        title.className = 'title';
        title.style.borderColor = d.hasOwnProperty('strokeColor') ? d.strokeColor : d.color;
        title.style.borderStyle = 'solid';
        parent.appendChild(title);

        var text = document.createTextNode(d.title);
        title.appendChild(text);
    });
}
</script>
<script>
var data = {
	labels : ["Avrora","Fop","Xalan"],
	datasets : [
		{
			fillColor : "rgba(0, 69, 134, 0.8)",
			strokeColor : "rgba(0, 69, 134,1)",
			data : [100,100,100],
            title : "JDK7 Soft Float - RPi"
		},
		{
			fillColor : "rgba(255, 66, 14, 0.8)",
			strokeColor : "rgba(255, 66, 14,1)",
			data : [21.76,41.23,30.35],
            title : "JDK7 Soft Float - BBB"
		},
		{
			fillColor : "rgba(255, 210, 31, 0.8)",
			strokeColor : "rgba(255, 210, 31,1)",
			data : [22.9,40,31.07],
            title : "JDK7 Hard Float - BBB"
		},
		{
			fillColor : "rgba(87, 157, 28, 0.8)",
			strokeColor : "rgba(87, 157, 28, 1)",
			data : [23.55,42.58,31.49],
            title : "JDK8 Hard Float - BBB"
		}        
	]
}
var data2 = {
	labels : ["Avrora","Fop","Xalan"],
	datasets : [
		{
			fillColor : "rgba(255, 66, 14, 0.8)",
			strokeColor : "rgba(255, 66, 14,1)",
			data : [21.76,41.23,30.35],
            title : "JDK7 Soft Float - BBB"
		},
		{
			fillColor : "rgba(255, 210, 31, 0.8)",
			strokeColor : "rgba(255, 210, 31,1)",
			data : [22.9,40,31.07],
            title : "JDK7 Hard Float - BBB"
		},
		{
			fillColor : "rgba(87, 157, 28, 0.8)",
			strokeColor : "rgba(87, 157, 28, 1)",
			data : [23.55,42.58,31.49],
            title : "JDK8 Hard Float - BBB"
		}        
	]
}
var options = {
    scaleOverride: true,
    scaleSteps : 5,
    scaleStepWidth: 20,
    scaleStartValue: 0
}
var options2 = {
    scaleOverride: true,
    scaleSteps : 5,
    scaleStepWidth: 10,
    scaleStartValue: 0
}

function draw() {
    var perfsWithRPi = document.getElementById("perfsWithRPi");
    perfsWithRPi.width = perfsWithRPi.parentNode.clientWidth - 30;
    perfsWithRPi.height=350;
    console.log(perfsWithRPi.width);
    var ctx = perfsWithRPi.getContext("2d");
    new Chart(ctx).Bar(data, options);

    var perfsWithoutRPi = document.getElementById("perfsWithoutRPi");
    perfsWithoutRPi.width = perfsWithoutRPi.parentNode.clientWidth - 30;
    perfsWithoutRPi.height=350;
    var ctx2 = perfsWithoutRPi.getContext("2d");
    new Chart(ctx2).Bar(data2, options2);
}
draw();
legend(document.getElementById("perfWithRPiLegend"), data);
legend(document.getElementById("perfWithoutRPiLegend"), data2);    

window.onresize = function() {
    /* Canvas à redessiner, responsive oblige ! */
    draw();
};
</script>
++++

En conclusion, les performances ne sont pas fondamentalement différentes. Si vous êtes sur l'OS de base sur la Beaglebone, vous n'avez donc pas besoin d'en changer ... sauf si vous voulez tester les nouveautés du JDK8.

Autre enseingement : Si vous faites tourner du code Java sur une Raspberry Pi, vous auriez avantage à passer sur Beaglebone Black !
